services:
  - type: web
    name: polypress-blog
    runtime: node
    buildCommand: npm ci && npm run build
    startCommand: node build/ace.js migration:run --force && node build/bin/server.js
    envVars:
      - key: NODE_VERSION
        value: 24
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: LOG_LEVEL
        value: info
      - key: SESSION_DRIVER
        value: cookie
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pg
      - key: DATABASE_URL
        sync: false
      - key: APP_URL
        value: https://polypress-blog.onrender.com
