/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Messages: () => import('#controllers/messages_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Reactions: () => import('#controllers/reactions_controller'),
  Session: () => import('#controllers/session_controller'),
  Admin: () => import('#controllers/admin_controller'),
}
